### ISSUE TITLE
Chequear las notificaciones que llegan tanto con la app abierta como cerrada

### ISSUE THREAD

**Issue by cristoj** [wildvat/recparenting_appmobile#10]

**Comment by chuajose** [comment]
Solo se muestran 3 tipos que llegan a traves de push:
-Cuando se crea un appoinment
-Cuendo alguien envia un mensaje
-Cuando el terapeuta ha iniciado un meeting
En el resto, cuando llegan simplemente muestra el icono en la perte superior indicando que tienes nuevas notificaciones
